# Generated by Django 5.0.7 on 2024-07-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_author_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
