name: CI Workflow

# Trigger the workflow on push to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
  
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: praveen
          MYSQL_DATABASE: hospital
        ports:
          - 3306:3306
        options: >-
            --health-cmd="mysqladmin ping --silent"
            --health-interval=10s
            --health-timeout=5s
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
    
    - name: Wait for MySQL to be ready
      run: |
        until mysqladmin ping -h 127.0.0.1 --silent; do
          echo "Waiting for MySQL to be ready..."
          sleep 3
        done

    - name: Run database migrations
      env: 
         DATABASE_URL: mysql://root:praveen@127.0.0.1:3306/hospital

      run: |
        python manage.py migrate

    - name: Run tests
      env:
         DATABASE_URL: mysql://root:praveen@127.0.0.1:3306/hospital
      run: pytest
