name: CI Workflow

# Trigger the workflow on push to the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
  
    services:
      mysql:
        image: mysql:5.8
        env:
          MYSQL_ROOT_PASSWORD: praveen
          MYSQL_DATABASE: hospital
        ports:
          - 3306:3306
        options: >-
            --health-cmd="mysqladmin ping --silent"
            --health-interval=10s
            --health-timeout=5s
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
    
    - name: Run database migrations
      run: |
        python manage.py migrate

    - name: Run tests
      run: pytest
